name: Update Dependencies
on:
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch:
jobs:
  update-dep:
    if: github.repository_owner == 'acowley'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Update nixpkgs
        run: nix flake update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'Automated nixpkgs bump'
          branch: automated-bump
          delete-branch: true
          title: 'Automated nixpkgs bump'          
